In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os
import glob

In [3]:
import pandas as pd

df_2015 = pd.read_csv("../dataset/amazon_india_2015.csv")
df_2016 = pd.read_csv("../dataset/amazon_india_2016.csv")
df_2017 = pd.read_csv("../dataset/amazon_india_2017.csv")
df_2018 = pd.read_csv("../dataset/amazon_india_2018.csv")
df_2019 = pd.read_csv("../dataset/amazon_india_2019.csv")
df_2020 = pd.read_csv("../dataset/amazon_india_2020.csv")
df_2021 = pd.read_csv("../dataset/amazon_india_2021.csv")
df_2022 = pd.read_csv("../dataset/amazon_india_2022.csv")
df_2023 = pd.read_csv("../dataset/amazon_india_2023.csv")
df_2024 = pd.read_csv("../dataset/amazon_india_2024.csv")
df_2025 = pd.read_csv("../dataset/amazon_india_2025.csv")

product_catalog = pd.read_csv("../dataset/amazon_india_products_catalog.csv")

In [4]:
print(df_2015.shape)
print(df_2016.shape)
print(df_2017.shape)
print(df_2018.shape)
print(df_2019.shape)
print(df_2020.shape)
print(df_2021.shape)
print(df_2022.shape)
print(df_2023.shape)
print(df_2024.shape)
print(df_2025.shape)
print(product_catalog.shape)

(33165, 34)
(55275, 34)
(77385, 34)
(99495, 34)
(121605, 34)
(143715, 34)
(138187, 34)
(132660, 34)
(127132, 34)
(121605, 34)
(77385, 34)
(2004, 11)

In [5]:
merged_df = pd.concat([
    df_2015,
    df_2016,
    df_2017,
    df_2018,
    df_2019,
    df_2020,
    df_2021,
    df_2022,
    df_2023,
    df_2024,
    df_2025
], ignore_index=True)

In [6]:
merged_df.shape

(1127609, 34)

In [7]:
merged_df.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,NaN,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,"21,947.26",0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,FALSE,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1

In [8]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127609 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1127609 non-null  object
 1   order_date              1127609 non-null  object
 2   customer_id             1127609 non-null  object
 3   product_id              1127609 non-null  object
 4   product_name            1127609 non-null  object
 5   category                1127609 non-null  object
 6   subcategory             1127609 non-null  object
 7   brand                   1127609 non-null  object
 8   original_price_inr      1127609 non-null  object
 9   discount_percent        1127609 non-null  float64
 10  discounted_price_inr    1127609 non-null  float64
 11  quantity                1127609 non-null  int64
 12  subtotal_inr            1127609 non-null  float64
 13  delivery_charges        1037408 non-null  float64
 14  final_amount_inr        1127609 non-null  float64
 15  customer_city           1127609 non-null  object
 16  customer_state          1127609 non-null  object
 17  customer_tier           1127609 non-null  object
 18  customer_spending_tier  1127609 non-null  object
 19  customer_age_group      992294 non-null   object
 20  payment_method          1127609 non-null  object
 21  delivery_days           1127609 non-null  object
 22  delivery_type           1127609 non-null  object
 23  is_prime_member         1127609 non-null  object
 24  is_festival_sale        1127609 non-null  object
 25  festival_name           349873 non-null   object
 26  customer_rating         785913 non-null   object
 27  return_status           1127609 non-null  object
 28  order_month             1127609 non-null  int64
 29  order_year              1127609 non-null  int64
 30  order_quarter           1127609 non-null  int64
 31  product_weight_kg       1127609 non-null  float64
 32  is_prime_eligible       1127609 non-null  object
 33  product_rating          1127609 non-null  float64
dtypes: float64(7), int64(4), object(23)
memory usage: 292.5+ MB

In [9]:
merged_df.columns

Index(['transaction_id', 'order_date', 'customer_id', 'product_id',
       'product_name', 'category', 'subcategory', 'brand',
       'original_price_inr', 'discount_percent', 'discounted_price_inr',
       'quantity', 'subtotal_inr', 'delivery_charges', 'final_amount_inr',
       'customer_city', 'customer_state', 'customer_tier',
       'customer_spending_tier', 'customer_age_group', 'payment_method',
       'delivery_days', 'delivery_type', 'is_prime_member', 'is_festival_sale',
       'festival_name', 'customer_rating', 'return_status', 'order_month',
       'order_year', 'order_quarter', 'product_weight_kg', 'is_prime_eligible',
       'product_rating'],
      dtype='object')

In [10]:
merged_df.isnull().sum()

transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges           90201
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group        135315
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             777736
customer_rating           341696
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64

In [11]:
merged_df.duplicated().sum()

0

In [12]:
merged_df.describe()

,discount_percent,discounted_price_inr,quantity,subtotal_inr,delivery_charges,final_amount_inr,order_month,order_year,order_quarter,product_weight_kg,product_rating
count,1.127609e+06,1.127609e+06,1.127609e+06,1.127609e+06,1.037408e+06,1.127609e+06,1.127609e+06,1.127609e+06,1.127609e+06,1.127609e+06,1.127609e+06
mean,1.742035e+01,5.454134e+04,1.250063e+00,6.818740e+04,3.084611e-04,6.818740e+04,6.940627e+00,2.020637e+03,2.645922e+00,7.806976e-01,3.975245e+00
std,2.055377e+01,4.582480e+04,5.365034e-01,6.893407e+04,1.110782e-01,6.893407e+04,3.539183e+00,2.690906e+00,1.140795e+00,3.674216e+00,4.536469e-01
min,0.000000e+00,3.443300e+02,1.000000e+00,3.443300e+02,0.000000e+00,3.443300e+02,1.000000e+00,2.015000e+03,1.000000e+00,3.000000e-02,3.000000e+00
25%,0.000000e+00,2.278069e+04,1.000000e+00,2.521799e+04,0.000000e+00,2.521799e+04,4.000000e+00,2.019000e+03,2.000000e+00,1.800000e-01,3.600000e+00
50%,1.037000e+01,3.800119e+04,1.000000e+00,4.473182e+04,0.000000e+00,4.473182e+04,7.000000e+00,2.021000e+03,3.000000e+00,2.100000e-01,4.000000e+00
75%,2.841000e+01,7.410332e+04,1.000000e+00,8.852179e+04,0.000000e+00,8.852179e+04,1.000000e+01,2.023000e+03,4.000000e+00,2.400000e-01,4.400000e+00
max,7.000000e+01,4.207048e+05,3.000000e+00,1.262114e+06,4.000000e+01,1.262114e+06,1.200000e+01,2.025000e+03,4.000000e+00,4.426000e+01,4.800000e+00

In [13]:
merged_df["order_date"].head(20)

0     2015-01-25
1     2015-01-05
2     2015-01-24
3     2015-01-28
4     2015-01-31
5     2015-01-04
6     2015-01-27
7     2015-01-08
8     2015-01-18
9     2015-01-03
10    2015-01-25
11    2015-01-15
12    2015-01-26
13    2015-01-11
14    2015-01-08
15    2015-01-07
16    2015-01-25
17    2015-01-08
18    2015-01-06
19    2015-01-11
Name: order_date, dtype: object

In [14]:
#

temp_dates = pd.to_datetime(merged_df["order_date"], format="%Y-%m-%d", errors="coerce")

merged_df[temp_dates.isna()]["order_date"].unique()[:20]

array(['01/17/2015', '26-01-2015', '15-01-2015', '16-01-2015',
       '06-01-2015', '02/01/2015', '13/01/2015', '01/26/2015',
       '21-01-2015', '07/01/2015', '23/01/2015', '29/01/2015',
       '01/20/2015', '14/01/2015', '09/01/2015', '01/01/2015',
       '20-01-2015', '15/01/2015', '22/01/2015', '01/28/2015'],
      dtype=object)

In [15]:
merged_df["order_date"] = pd.to_datetime(
    merged_df["order_date"],
    format="mixed",
    dayfirst=True
)

In [16]:
merged_df["order_date"].dtype

dtype('<M8[ns]')

In [17]:
merged_df.to_csv(
    "C:/Users/CHARU/OneDrive/Desktop/Amazon sales p2/cleaned_data/merged_dataset.csv",
    index=False
)

In [18]:
# ============================================
# PROJECT PHASE 2 - DATA CLEANING
# Question 1
# Standardize the order_date column
# ============================================

merged_df["order_date"] = pd.to_datetime(
    merged_df["order_date"],
    format="mixed",
    dayfirst=True
)

merged_df["order_date"].dtype

dtype('<M8[ns]')

In [23]:
# ============================================
# PROJECT PHASE 2 - DATA CLEANING
# Question 2
# Inspect original_price_inr column
# ============================================

merged_df["original_price_inr"].head(20)
merged_df["original_price_inr"].dtype

dtype('O')

In [24]:
merged_df[merged_df["original_price_inr"].str.contains(",", na=False)].head(20)

Empty DataFrame
Columns: [transaction_id, order_date, customer_id, product_id, product_name, category, subcategory, brand, original_price_inr, discount_percent, discounted_price_inr, quantity, subtotal_inr, delivery_charges, final_amount_inr, customer_city, customer_state, customer_tier, customer_spending_tier, customer_age_group, payment_method, delivery_days, delivery_type, is_prime_member, is_festival_sale, festival_name, customer_rating, return_status, order_month, order_year, order_quarter, product_weight_kg, is_prime_eligible, product_rating]
Index: []

[0 rows x 34 columns]

In [25]:
merged_df["original_price_inr"].apply(type).value_counts()

original_price_inr
<class 'str'>    1127609
Name: count, dtype: int64

In [26]:
pd.to_numeric(merged_df["original_price_inr"], errors="coerce").isnull().sum()

78908

In [27]:
invalid_price = merged_df[
    pd.to_numeric(merged_df["original_price_inr"], errors="coerce").isnull()
]

invalid_price["original_price_inr"].unique()[:20]

array(['₹56337.89', '₹22683.69', 'Rs 47979', 'Rs 24762', 'Rs 21212',
       '₹173203.42', '₹54731.86', '₹31102.54', 'Rs 46234', '₹39010.09',
       '₹24762.02', '₹88664.85', 'Rs 39491', '₹74885.61', 'Rs 36351',
       '₹42790.64', 'Rs 130430', '₹20323.89', 'Rs 17869', 'Rs 22684'],
      dtype=object)

In [28]:
merged_df["original_price_inr"] = (
    merged_df["original_price_inr"]
    .str.replace("₹", "", regex=False)
    .str.replace("Rs ", "", regex=False)
)

In [29]:
merged_df["original_price_inr"].head(20)

0     123614.29
1      54731.86
2      97644.25
3      21947.26
4      54731.86
5     131194.65
6      86987.64
7      32169.01
8      40264.16
9      54731.86
10     88664.85
11     73967.02
12      72564.1
13    209875.55
14     45363.47
15     23075.71
16     23075.71
17    114096.63
18     69584.33
19     38884.19
Name: original_price_inr, dtype: object

In [30]:
merged_df["original_price_inr"] = merged_df["original_price_inr"].astype(float)

In [31]:
merged_df["original_price_inr"].dtype

dtype('float64')

In [32]:
# ==========================================================
# PROJECT PHASE 2 : DATA CLEANING
# ==========================================================
# Question 3:
# Customer ratings appear in various formats such as
# '5.0', '4 stars', '3/5', '2.5/5.0' and some missing values.
#
# Objective:
# Inspect the customer_rating column to identify different
# rating formats and missing values before cleaning and
# standardizing them into a numeric scale (1.0 - 5.0).
# ==========================================================

merged_df["customer_rating"].head(20)

0           5.0
1           4.5
2           NaN
3           3.0
4           4.0
5           4.5
6           3.5
7           4.0
8           5.0
9           4.5
10          5.0
11          4.5
12          NaN
13          4/5
14          4.5
15          NaN
16    5.0 stars
17          NaN
18          4.5
19          NaN
Name: customer_rating, dtype: object

In [33]:
merged_df["customer_rating"].dtype

dtype('O')

In [34]:
merged_df["customer_rating"].unique()[:20]

array(['5.0', '4.5', nan, '3.0', '4.0', '3.5', '4/5', '5.0 stars',
       '5.0/5.0', '4.5 stars', '3.5/5.0', '3/5', '4', '4.0 stars',
       '4.5/5.0', '5', '5/5', '4.0/5.0', '3.5 stars', '3.0 stars'],
      dtype=object)

In [35]:
merged_df["customer_rating"].isnull().sum()

341696

In [36]:
# ==========================================================
# Cleaning customer_rating column
# Remove the word "stars"
# ==========================================================

merged_df["customer_rating"] = merged_df["customer_rating"].str.replace(" stars", "", regex=False)

In [37]:
merged_df["customer_rating"].unique()[:20]

array(['5.0', '4.5', nan, '3.0', '4.0', '3.5', '4/5', '5.0/5.0',
       '3.5/5.0', '3/5', '4', '4.5/5.0', '5', '5/5', '4.0/5.0', '3',
       '3.0/5.0'], dtype=object)

In [38]:
# ==========================================================
# Remove '/5' and '/5.0' from customer_rating
# ==========================================================

merged_df["customer_rating"] = merged_df["customer_rating"].str.split("/").str[0]

In [39]:
merged_df["customer_rating"].unique()[:20]

array(['5.0', '4.5', nan, '3.0', '4.0', '3.5', '4', '3', '5'],
      dtype=object)

In [40]:
# ==========================================================
# Convert customer_rating to numeric data type
# ==========================================================

merged_df["customer_rating"] = pd.to_numeric(
    merged_df["customer_rating"],
    errors="coerce"
)

In [41]:
merged_df["customer_rating"].dtype

dtype('float64')

In [42]:
merged_df["customer_rating"].isnull().sum()

341696

In [43]:
# ==========================================================
# Find the average customer rating
# ==========================================================

merged_df["customer_rating"].mean()

4.310750681055028

In [44]:
# ==========================================================
# Fill missing customer ratings with the average rating
# ==========================================================

merged_df["customer_rating"] = merged_df["customer_rating"].fillna(
    merged_df["customer_rating"].mean()
)

In [45]:
# Check missing values after filling

merged_df["customer_rating"].isnull().sum()

0

In [46]:
# Verify the cleaned customer_rating column

merged_df["customer_rating"].head(20)

0     5.000000
1     4.500000
2     4.310751
3     3.000000
4     4.000000
5     4.500000
6     3.500000
7     4.000000
8     5.000000
9     4.500000
10    5.000000
11    4.500000
12    4.310751
13    4.000000
14    4.500000
15    4.310751
16    5.000000
17    4.310751
18    4.500000
19    4.310751
Name: customer_rating, dtype: float64

In [47]:
# ==========================================================
# PROJECT PHASE 2 : DATA CLEANING
# ==========================================================
# Question 4:
# The customer_city column contains inconsistent city names
# such as Bangalore/Bengaluru, Mumbai/Bombay,
# Delhi/New Delhi, spelling mistakes, and case variations.
#
# Objective:
# Inspect the customer_city column, identify inconsistent
# city names, and standardize them into a single,
# consistent format across the dataset.
# ==========================================================

merged_df["customer_city"].head(20)

0          Mumbai
1       Allahabad
2          Mumbai
3         Kolkata
4        Ludhiana
5           Delhi
6         Lucknow
7          Jaipur
8           Delhi
9     Bhubaneswar
10      Ahmedabad
11      Bangalore
12          Delhi
13         Mumbai
14      Bangalore
15           Pune
16          Kochi
17        Chennai
18        Chennai
19         Mumbai
Name: customer_city, dtype: object

In [48]:
merged_df["customer_city"].dtype

dtype('O')

In [49]:
merged_df["customer_city"].unique()[:30]

array(['Mumbai', 'Allahabad', 'Kolkata', 'Ludhiana', 'Delhi', 'Lucknow',
       'Jaipur', 'Bhubaneswar', 'Ahmedabad', 'Bangalore', 'Pune', 'Kochi',
       'Chennai', 'Nagpur', 'Visakhapatnam', 'mumba', 'Gorakhpur',
       'Bombay', 'Kanpur', 'Chandigarh', 'Hyderabad', 'Aligarh', 'Indore',
       'Patna', 'Meerut', 'Coimbatore', 'Vadodara', 'Saharanpur',
       'Bareilly', 'BANGALORE'], dtype=object)

In [50]:
# ==========================================================
# Standardize customer city names
# ==========================================================

merged_df["customer_city"] = merged_df["customer_city"].replace({
    "mumbai": "Mumbai",
    "Bombay": "Mumbai",
    "BANGALORE": "Bangalore",
    "Bengaluru": "Bangalore",
    "New Delhi": "Delhi"
})

In [51]:
merged_df["customer_city"].unique()[:30]

array(['Mumbai', 'Allahabad', 'Kolkata', 'Ludhiana', 'Delhi', 'Lucknow',
       'Jaipur', 'Bhubaneswar', 'Ahmedabad', 'Bangalore', 'Pune', 'Kochi',
       'Chennai', 'Nagpur', 'Visakhapatnam', 'mumba', 'Gorakhpur',
       'Kanpur', 'Chandigarh', 'Hyderabad', 'Aligarh', 'Indore', 'Patna',
       'Meerut', 'Coimbatore', 'Vadodara', 'Saharanpur', 'Bareilly',
       'Moradabad', 'Surat'], dtype=object)

In [52]:
# ==========================================================
# Correct remaining spelling mistakes
# ==========================================================

merged_df["customer_city"] = merged_df["customer_city"].replace({
    "mumba": "Mumbai"
})

In [53]:
merged_df["customer_city"].unique()[:30]

array(['Mumbai', 'Allahabad', 'Kolkata', 'Ludhiana', 'Delhi', 'Lucknow',
       'Jaipur', 'Bhubaneswar', 'Ahmedabad', 'Bangalore', 'Pune', 'Kochi',
       'Chennai', 'Nagpur', 'Visakhapatnam', 'Gorakhpur', 'Kanpur',
       'Chandigarh', 'Hyderabad', 'Aligarh', 'Indore', 'Patna', 'Meerut',
       'Coimbatore', 'Vadodara', 'Saharanpur', 'Bareilly', 'Moradabad',
       'Surat', 'KOLKATA'], dtype=object)

In [54]:
# ==========================================================
# Correct remaining spelling and case variations
# ==========================================================

merged_df["customer_city"] = merged_df["customer_city"].replace({
    "KOLKATA": "Kolkata"
})

In [55]:
merged_df["customer_city"].unique()[:30]

array(['Mumbai', 'Allahabad', 'Kolkata', 'Ludhiana', 'Delhi', 'Lucknow',
       'Jaipur', 'Bhubaneswar', 'Ahmedabad', 'Bangalore', 'Pune', 'Kochi',
       'Chennai', 'Nagpur', 'Visakhapatnam', 'Gorakhpur', 'Kanpur',
       'Chandigarh', 'Hyderabad', 'Aligarh', 'Indore', 'Patna', 'Meerut',
       'Coimbatore', 'Vadodara', 'Saharanpur', 'Bareilly', 'Moradabad',
       'Surat', 'Banglore'], dtype=object)

In [56]:
# ==========================================================
# PROJECT PHASE 2 - DATA CLEANING
# Question 5
#
# The boolean columns (is_prime_member,
# is_prime_eligible, is_festival_sale) contain
# mixed values such as True/False, Yes/No,
# 1/0, Y/N and missing values.
#
# Objective:
# Convert all boolean columns into a
# consistent True/False format.
# ==========================================================

merged_df[["is_prime_member",
           "is_prime_eligible",
           "is_festival_sale"]].head(20)

   is_prime_member is_prime_eligible is_festival_sale
0               No              True             True
1            False              True            False
2            False              True             True
3            False              True            False
4            False              True            FALSE
5            False                No            False
6            False             False            False
7            False             False            False
8            False              True            False
9            False              True            False
10              No              True             True
11           False              True            False
12           False              True             True
13           False              True            False
14           False             False            False
15              No              True            False
16           False              True             True
17           False              True            False
18           False              True            False
19           False             False            False

In [57]:
merged_df[["is_prime_member",
           "is_prime_eligible",
           "is_festival_sale"]].dtypes

is_prime_member      object
is_prime_eligible    object
is_festival_sale     object
dtype: object

In [58]:
merged_df["is_prime_member"].unique()
merged_df["is_prime_eligible"].unique()
merged_df["is_festival_sale"].unique()

array(['True', 'False', 'FALSE', 'No', '0', '1', 'Yes', 'TRUE'],
      dtype=object)

In [59]:
# ==========================================================
# Standardize is_prime_member values
# ==========================================================

merged_df["is_prime_member"] = merged_df["is_prime_member"].replace({
    "TRUE": "True",
    "FALSE": "False",
    "Yes": "True",
    "No": "False",
    "1": "True",
    "0": "False"
})

In [60]:
# ==========================================================
# Standardize is_prime_eligible values
# ==========================================================

merged_df["is_prime_eligible"] = merged_df["is_prime_eligible"].replace({
    "TRUE": "True",
    "FALSE": "False",
    "Yes": "True",
    "No": "False",
    "1": "True",
    "0": "False"
})

In [61]:
# ==========================================================
# Standardize is_festival_sale values
# ==========================================================

merged_df["is_festival_sale"] = merged_df["is_festival_sale"].replace({
    "TRUE": "True",
    "FALSE": "False",
    "Yes": "True",
    "No": "False",
    "1": "True",
    "0": "False"
})

In [62]:
merged_df["is_prime_member"].unique()
merged_df["is_prime_eligible"].unique()
merged_df["is_festival_sale"].unique()

array(['True', 'False'], dtype=object)

In [64]:
# ==========================================================
# PROJECT PHASE 2 - DATA CLEANING
# Question 6
#
# Product categories have variations such as
# Electronics/Electronic/ELECTRONICS/
# Electronics & Accessories.
#
# Objective:
# Standardize all product category names into
# a consistent format.
# ==========================================================

merged_df["category"].head(20)

0     Electronics
1     Electronics
2     Electronics
3     Electronics
4     Electronics
5     Electronics
6     Electronics
7     Electronics
8     Electronics
9     Electronics
10    ELECTRONICS
11    Electronics
12    Electronics
13    Electronics
14    Electronics
15    Electronics
16    Electronics
17    Electronics
18    Electronics
19    Electronics
Name: category, dtype: object

In [65]:
merged_df["category"].head(20)

0     Electronics
1     Electronics
2     Electronics
3     Electronics
4     Electronics
5     Electronics
6     Electronics
7     Electronics
8     Electronics
9     Electronics
10    ELECTRONICS
11    Electronics
12    Electronics
13    Electronics
14    Electronics
15    Electronics
16    Electronics
17    Electronics
18    Electronics
19    Electronics
Name: category, dtype: object

In [66]:
merged_df["category"].dtype

dtype('O')

In [67]:
merged_df["category"].unique()

array(['Electronics', 'ELECTRONICS', 'Electronics & Accessories',
       'Electronic', 'Electronicss'], dtype=object)

In [68]:
# ==========================================================
# Standardize product category names
# ==========================================================

merged_df["category"] = merged_df["category"].replace({
    "ELECTRONICS": "Electronics",
    "Electronic": "Electronics",
    "Electronicss": "Electronics",
    "Electronics & Accessories": "Electronics"
})

In [69]:
merged_df["category"].unique()

array(['Electronics'], dtype=object)

In [70]:
# ==========================================================
# PROJECT PHASE 2 - DATA CLEANING
# Question 7
#
# The delivery_days column contains negative values,
# text entries like 'Same Day', '1-2 days', and
# unrealistic values like 50 days.
#
# Objective:
# Clean the delivery_days column and convert it
# into valid numeric delivery days.
# ==========================================================

merged_df["delivery_days"].head(20)

0     6
1     4
2     4
3     4
4     3
5     3
6     4
7     3
8     3
9     5
10    4
11    3
12    4
13    4
14    4
15    4
16    5
17    7
18    3
19    5
Name: delivery_days, dtype: object

In [71]:
merged_df["delivery_days"].dtype

dtype('O')

In [72]:
merged_df["delivery_days"].unique()[:30]

array(['6', '4', '3', '5', '7', 'Express', '0', '-1', 'Same Day',
       '1-2 days', '15', '1', '2'], dtype=object)

In [73]:
merged_df["delivery_days"].isnull().sum()

0

In [74]:
# ==========================================================
# Replace text values with numeric delivery days
# ==========================================================

merged_df["delivery_days"] = merged_df["delivery_days"].replace({
    "Same Day": "0",
    "1-2 days": "2",
    "Express": "1"
})

In [75]:
# ==========================================================
# Convert delivery_days to numeric
# ==========================================================

merged_df["delivery_days"] = pd.to_numeric(
    merged_df["delivery_days"],
    errors="coerce"
)

In [76]:
# ==========================================================
# Replace negative delivery days
# ==========================================================

merged_df.loc[
    merged_df["delivery_days"] < 0,
    "delivery_days"
] = 1

In [77]:
merged_df["delivery_days"].unique()

array([ 6,  4,  3,  5,  7,  1,  0,  2, 15], dtype=int64)

In [78]:
merged_df["delivery_days"].dtype

dtype('int64')

In [79]:
merged_df["delivery_days"].head(20)

0     6
1     4
2     4
3     4
4     3
5     3
6     4
7     3
8     3
9     5
10    4
11    3
12    4
13    4
14    4
15    4
16    5
17    7
18    3
19    5
Name: delivery_days, dtype: int64

In [80]:
# ==========================================================
# PROJECT PHASE 2 - DATA CLEANING
# Question 8
# Identify and handle duplicate transactions
# # ==========================================================

merged_df[[
    "customer_id",
    "product_id",
    "order_date",
    "original_price_inr"
]].head(20)

           customer_id   product_id order_date  original_price_inr
0   CUST_2015_00003884  PROD_000021 2015-01-25           123614.29
1   CUST_2015_00011709  PROD_000055 2015-01-05            54731.86
2   CUST_2015_00004782  PROD_000039 2015-01-24            97644.25
3   CUST_2015_00008105  PROD_000085 2015-01-28            21947.26
4   CUST_2015_00002955  PROD_000055 2015-01-31            54731.86
5   CUST_2015_00006757  PROD_001665 2015-01-04           131194.65
6   CUST_2015_00008012  PROD_000031 2015-01-27            86987.64
7   CUST_2015_00011809  PROD_000048 2015-01-08            32169.01
8   CUST_2015_00006429  PROD_000082 2015-01-18            40264.16
9   CUST_2015_00001829  PROD_000055 2015-01-03            54731.86
10  CUST_2015_00005519  PROD_000037 2015-01-25            88664.85
11  CUST_2015_00005472  PROD_001693 2015-01-15            73967.02
12  CUST_2015_00010786  PROD_000052 2015-01-26            72564.10
13  CUST_2015_00004676  PROD_000006 2015-01-11           209875.55
14  CUST_2015_00008208  PROD_001935 2015-01-08            45363.47
15  CUST_2015_00010560  PROD_001849 2015-01-07            23075.71
16  CUST_2015_00007705  PROD_001849 2015-01-25            23075.71
17  CUST_2015_00004883  PROD_000009 2015-01-08           114096.63
18  CUST_2015_00011225  PROD_001640 2015-01-06            69584.33
19  CUST_2015_00008851  PROD_001983 2015-01-11            38884.19

In [81]:
merged_df.duplicated(
    subset=[
        "customer_id",
        "product_id",
        "order_date",
        "original_price_inr"
    ]
).sum()

5521

In [82]:
# ==========================================================
# Display duplicate transactions
# ==========================================================

duplicate_transactions = merged_df[
    merged_df.duplicated(
        subset=[
            "customer_id",
            "product_id",
            "order_date",
            "original_price_inr"
        ],
        keep=False
    )
]

duplicate_transactions.head(20)

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
279,TXN_2015_00000280,2015-01-29,CUST_2015_00010848,PROD_000027,Samsung Galaxy S6 16GB Blue,Electronics,Smartphones,Samsung,130430.00,21.03,...,False,NaN,4.000000,Delivered,1,2015,1,0.18,True,3.4
814,TXN_2015_00000815,2015-01-31,CUST_2015_00001928,PROD_000059,OnePlus OnePlus X 32GB Black,Electronics,Smartphones,OnePlus,57182.39,0.00,...,False,NaN,5.000000,Delivered,1,2015,1,0.20,True,3.8
941,TXN_2015_00000942,2015-01-03,CUST_2015_00007653,PROD_000075,Xiaomi Redmi 2 64GB White,Electronics,Smartphones,Xiaomi,35581.67,0.00,...,False,NaN,4.310751,Delivered,1,2015,1,0.22,False,3.6
996,TXN_2015_00000997,2015-01-28,CUST_2015_00003254,PROD_000032,Samsung Galaxy S6 Edge 16GB White,Electronics,Smartphones,Samsung,97905.92,0.00,...,False,NaN,4.000000,Delivered,1,2015,1,0.20,True,4.3
1390,TXN_2015_00001391,2015-01-15,CUST_2015_00005080,PROD_001640,MSI Aspire 4GB RAM Black,Electronics,Laptops,MSI,69584.33,12.76,...,False,NaN,4.500000,Returned,1,2015,1,2.66,True,3.2
1577,TXN_2015_00001578,2015-01-24,CUST_2015_00002994,PROD_000063,OnePlus OnePlus X 32GB Blue,Electronics,Smartphones,OnePlus,75380.48,45.58,...,True,Republic Day Sale,5.000000,Delivered,1,2015,1,0.18,True,3.8
1626,TXN_2015_00001627,2015-01-12,CUST_2015_00007323,PROD_000070,Xiaomi Redmi 2 16GB Black,Electronics,Smartphones,Xiaomi,29534.70,6.24,...,False,NaN,4.310751,Delivered,1,2015,1,0.20,True,4.2
1809,TXN_2015_00001810,2015-01-31,CUST_2015_00005511,PROD_000070,Xiaomi Redmi 2 16GB Black,Electronics,Smartphones,Xiaomi,29534.70,26.41,...,False,NaN,4.500000,Delivered,1,2015,1,0.20,True,4.2
1851,TXN_2015_00001852,2015-01-23,CUST_2015_00000037,PROD_000053,OnePlus OnePlus 2 32GB Black,Electronics,Smartphones,OnePlus,102649.14,19.30,...,True,Republic Day Sale,5.000000,Delivered,1,2015,1,0.20,True,4.6
1999,TXN_2015_00002000,2015-01-01,CUST_2015_00008125,PROD_000060,OnePlus OnePlus X 16GB White,Electronics,Smartphones,OnePlus,94029.64,0.00,...,False,NaN,4.000000,Returned,1,2015,1,0.24,True,3.3
2137,TXN_2015_00002138,2015-01-17,CUST_2015_00010624,PROD_001935,Garmin Watch Deluxe,Electronics,Smart Watch,Garmin,45363.47,0.00,...,False,NaN,4.500000,Delivered,1,2015,1,0.08,False,4.8
2271,TXN_2015_00002272,2015-01-28,CUST_2015_00000924,PROD_000077,Xiaomi Redmi 2 32GB Blue,Electronics,Smartphones,Xiaomi,20175.12,0.00,...,False,NaN,5.000000,Delivered,1,2015,1,0.19,True,4.3
2325,TXN_2015_00002326,2015-01-20,CUST_2015_00003918,PROD_000072,Xiaomi Redmi 2 64GB Black,Electronics,Smartphones,Xiaomi,20937.46,51.66,...,True,Republic Day Sale,4.500000,Returned,1,2015,1,0.19,True,3.3
2469,TXN_2015_00002470,2015-02-19,CUST_2015_00010413,PROD_001957,Noise Sports Watch Premium,Electronics,Smart Watch,Noise,37013.54,0.00,...,False,NaN,5.000000,Delivered,2,2015,1,0.03,False,4.2
2570,TXN_2015_00002571,2015-02-28,CUST_2015_00002667,PROD_001546,Dell MacBook 4GB RAM Silver,Electronics,Laptops,Dell,29350.42,0.00,...,False,NaN,4.310751,Delivered,2,2015,1,1.21,True,3.4
2757,TXN_2015_00002758,2015-02-17,CUST_2015_00010349,PROD_000016,Apple iPhone 6 Plus 32GB Blue,Electronics,Smartphones,Apple,173203.42,0.00,...,False,NaN,5.000000,Delivered,2,2015,1,0.18,True,3.6
2842,TXN_2015_00002843,2015-02-08,CUST_2015_00010811,PROD_000096,Motorola Moto X Play 32GB White,Electronics,Smartphones,Motorola,24160.32,14.95,...,False,NaN,4.310751,Delivered,2,2015,1,0.21,True,4.1
3063,TXN_2015_00003064,2015-02-03,CUST_2015_00010660,PROD_000001,Apple iPhone 6 16GB Black,Electronics,Smartphones,Apple,190469.10,17.90,...,False,NaN,4.310751,Delivered,2,2015,1,0.21,True,3.9
3264,TXN_2015_00003265,2015-02-08,CUST_2015_00000492,PROD_001671,Alienware Ultrabook 4GB RAM Black,Electronics,Laptops,Alienware,107387.37,0.00,...,False,NaN,4.000000,Delivered,2,2015,1,2.33,True,4.7
3434,TXN_2015_00003435,2015-02-17,CUST_2015_00006925,PROD_001524,HP Inspiron 8GB RAM Black,Electronics,Laptops,HP,184704.89,8.09,...,False,NaN,4.000000,Delivered,2,2015,1,2.60,True,3.9

In [83]:
# ==========================================================
# Count duplicate rows
# ==========================================================

len(duplicate_transactions)

11042

In [84]:
# ==========================================================
# Strategy
# ==========================================================

print("Duplicate transactions identified.")
print("Duplicates are kept because they may represent genuine bulk orders.")

Duplicate transactions identified.
Duplicates are kept because they may represent genuine bulk orders.

Duplicate transactions identified.
Duplicates are kept because they may represent genuine bulk orders.

In [86]:
# ==========================================================
# PROJECT PHASE 2 - DATA CLEANING
# Question 9
# Identify outlier prices
# ==========================================================

merged_df["original_price_inr"].describe()

count    1.127609e+06
mean     8.230271e+04
std      4.049590e+05
min     -3.001027e+05
25%      2.883210e+04
50%      4.654833e+04
75%      9.420046e+04
max      3.337169e+07
Name: original_price_inr, dtype: float64

In [87]:
# ==========================================================
# Find Q1 and Q3
# ==========================================================

Q1 = merged_df["original_price_inr"].quantile(0.25)
Q3 = merged_df["original_price_inr"].quantile(0.75)

print("Q1 =", Q1)
print("Q3 =", Q3)

Q1 = 28832.1
Q3 = 94200.46

In [88]:
# ==========================================================
# Calculate IQR
# ==========================================================

IQR = Q3 - Q1

print("IQR =", IQR)

IQR = 65368.36000000001

In [89]:
# ==========================================================
# Find lower and upper limits
# ==========================================================

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Lower Limit =", lower_limit)
print("Upper Limit =", upper_limit)

Lower Limit = -69220.44
Upper Limit = 192253.0

In [90]:
# ==========================================================
# Count outliers
# ==========================================================

outliers = merged_df[
    (merged_df["original_price_inr"] < lower_limit) |
    (merged_df["original_price_inr"] > upper_limit)
]

len(outliers)

41349

In [91]:
# ==========================================================
# Replace lower outliers
# ==========================================================

merged_df.loc[
    merged_df["original_price_inr"] < lower_limit,
    "original_price_inr"
] = lower_limit

In [92]:
# ==========================================================
# Replace upper outliers
# ==========================================================

merged_df.loc[
    merged_df["original_price_inr"] > upper_limit,
    "original_price_inr"
] = upper_limit

In [93]:
# ==========================================================
# Verify cleaned prices
# ==========================================================

merged_df["original_price_inr"].describe()

count    1.127609e+06
mean     6.515156e+04
std      4.841412e+04
min     -6.922044e+04
25%      2.883210e+04
50%      4.654833e+04
75%      9.420046e+04
max      1.922530e+05
Name: original_price_inr, dtype: float64

In [94]:
# ===========================================================
# PROJECT PHASE 2 - DATA CLEANING
# Question 10
# Standardize payment methods
# ===========================================================

merged_df["payment_method"].head(20)
merged_df["payment_method"].dtype
merged_df["payment_method"].unique()

array(['COD', 'Debit Card', 'Credit Card', 'Net Banking', 'UPI', 'Wallet',
       'BNPL'], dtype=object)

In [95]:
merged_df["payment_method"] = merged_df["payment_method"].replace({
    "UPI": "UPI",
    "PhonePe": "UPI",
    "GooglePay": "UPI",
    "GPay": "UPI",

    "Credit Card": "Credit Card",
    "CREDIT_CARD": "Credit Card",
    "CC": "Credit Card",

    "Cash on Delivery": "Cash on Delivery",
    "COD": "Cash on Delivery",
    "C.O.D": "Cash on Delivery"
})

In [96]:
merged_df["payment_method"].unique()

array(['Cash on Delivery', 'Debit Card', 'Credit Card', 'Net Banking',
       'UPI', 'Wallet', 'BNPL'], dtype=object)

In [97]:
# ===========================================================
# Verify payment_method data type
# ===========================================================

merged_df["payment_method"].dtype

dtype('O')

In [98]:
# ===========================================================
# Verify standardized payment methods
# ===========================================================

merged_df["payment_method"].unique()

array(['Cash on Delivery', 'Debit Card', 'Credit Card', 'Net Banking',
       'UPI', 'Wallet', 'BNPL'], dtype=object)

In [99]:
# ===========================================================
# Save cleaned dataset
# ===========================================================

merged_df.to_csv("../cleaned_data/amazon_india_cleaned.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.